package lab7_miguelrojas;

import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        Usuarios master = new Usuarios("leobanegas", "99", "Leonardo", 22);
        au.getLista_usuarios().add(master);
        au.escribirArchivoU();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearUsuario = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jb_crearUsuario = new javax.swing.JButton();
        tf_usuarioU = new javax.swing.JTextField();
        pf_passwordUser = new javax.swing.JPasswordField();
        tf_nombreUser = new javax.swing.JTextField();
        js_edadUser = new javax.swing.JSpinner();
        jd_crearSolista = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_usuarioSolista = new javax.swing.JTextField();
        pf_passwordSolista = new javax.swing.JPasswordField();
        tf_nombreSolista = new javax.swing.JTextField();
        tf_generoMusicalSolista = new javax.swing.JTextField();
        js_edadSolista = new javax.swing.JSpinner();
        jb_crearSolista = new javax.swing.JButton();
        jd_crearBanda = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_usuarioBanda = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        js_integrantes = new javax.swing.JSpinner();
        tf_generoM_banda = new javax.swing.JTextField();
        tf_nombreBanda = new javax.swing.JTextField();
        pf_passwordBanda = new javax.swing.JPasswordField();
        jb_registrarBanda = new javax.swing.JButton();
        jd_menuLeo = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jd_ProgressBarCuenta = new javax.swing.JDialog();
        jpb_cuenta = new javax.swing.JProgressBar();
        jLabel15 = new javax.swing.JLabel();
        jd_menuUser = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jd_menuSolista = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jd_menuBanda = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuarioMain = new javax.swing.JTextField();
        pf_passwordMain = new javax.swing.JPasswordField();
        jb_login = new javax.swing.JButton();
        jb_registrarse = new javax.swing.JButton();
        cb_tipo_usuario = new javax.swing.JComboBox<>();

        jLabel4.setText("Registrar Usuario");

        jLabel5.setText("Usuario");

        jLabel6.setText("Contrasena");

        jLabel7.setText("Nombre");

        jLabel8.setText("Edad");

        jb_crearUsuario.setText("Crear Usuario");
        jb_crearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearUsuarioMouseClicked(evt);
            }
        });

        js_edadUser.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(js_edadUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_usuarioU, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(pf_passwordUser)
                                .addComponent(tf_nombreUser)))))
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_crearUsuario)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_usuarioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(pf_passwordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(js_edadUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jb_crearUsuario)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout jd_crearUsuarioLayout = new javax.swing.GroupLayout(jd_crearUsuario.getContentPane());
        jd_crearUsuario.getContentPane().setLayout(jd_crearUsuarioLayout);
        jd_crearUsuarioLayout.setHorizontalGroup(
            jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_crearUsuarioLayout.setVerticalGroup(
            jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Crear Solista");

        jLabel10.setText("Usuario");

        jLabel11.setText("Contraseña");

        jLabel12.setText("Nombre");

        jLabel13.setText("Genero Musical");

        jLabel14.setText("Edad");

        jb_crearSolista.setText("Crear Solista");
        jb_crearSolista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearSolistaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearSolistaLayout = new javax.swing.GroupLayout(jd_crearSolista.getContentPane());
        jd_crearSolista.getContentPane().setLayout(jd_crearSolistaLayout);
        jd_crearSolistaLayout.setHorizontalGroup(
            jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearSolistaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jd_crearSolistaLayout.createSequentialGroup()
                        .addGroup(jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(29, 29, 29)
                        .addGroup(jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(js_edadSolista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_usuarioSolista)
                                .addComponent(pf_passwordSolista)
                                .addComponent(tf_nombreSolista)
                                .addComponent(tf_generoMusicalSolista, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearSolistaLayout.createSequentialGroup()
                .addContainerGap(558, Short.MAX_VALUE)
                .addComponent(jb_crearSolista)
                .addGap(118, 118, 118))
        );
        jd_crearSolistaLayout.setVerticalGroup(
            jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearSolistaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addGap(51, 51, 51)
                .addGroup(jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_usuarioSolista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pf_passwordSolista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_nombreSolista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_generoMusicalSolista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_crearSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(js_edadSolista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jb_crearSolista, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        jLabel16.setText("Registrar Banda");

        jLabel17.setText("Usuario");

        jLabel18.setText("Contraseña");

        jLabel19.setText("Nombre");

        jLabel20.setText("Genero Musical");

        jLabel21.setText("Numero de Integrantes");

        jb_registrarBanda.setText("Registrar");
        jb_registrarBanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarBandaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_usuarioBanda, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(js_integrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pf_passwordBanda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(tf_generoM_banda, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_nombreBanda, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_registrarBanda)
                .addGap(152, 152, 152))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel16)
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_usuarioBanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(pf_passwordBanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tf_nombreBanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(tf_generoM_banda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel21))
                    .addComponent(js_integrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jb_registrarBanda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_crearBandaLayout = new javax.swing.GroupLayout(jd_crearBanda.getContentPane());
        jd_crearBanda.getContentPane().setLayout(jd_crearBandaLayout);
        jd_crearBandaLayout.setHorizontalGroup(
            jd_crearBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearBandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_crearBandaLayout.setVerticalGroup(
            jd_crearBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearBandaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel22.setText("Menu de Leo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel22)
                .addContainerGap(627, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel22)
                .addContainerGap(453, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_menuLeoLayout = new javax.swing.GroupLayout(jd_menuLeo.getContentPane());
        jd_menuLeo.getContentPane().setLayout(jd_menuLeoLayout);
        jd_menuLeoLayout.setHorizontalGroup(
            jd_menuLeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuLeoLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_menuLeoLayout.setVerticalGroup(
            jd_menuLeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuLeoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jd_ProgressBarCuenta.setMaximumSize(new java.awt.Dimension(50, 50));

        jpb_cuenta.setMaximum(10);

        jLabel15.setText("Creando Cuenta.........");

        javax.swing.GroupLayout jd_ProgressBarCuentaLayout = new javax.swing.GroupLayout(jd_ProgressBarCuenta.getContentPane());
        jd_ProgressBarCuenta.getContentPane().setLayout(jd_ProgressBarCuentaLayout);
        jd_ProgressBarCuentaLayout.setHorizontalGroup(
            jd_ProgressBarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ProgressBarCuentaLayout.createSequentialGroup()
                .addGroup(jd_ProgressBarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ProgressBarCuentaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel15))
                    .addGroup(jd_ProgressBarCuentaLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jpb_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jd_ProgressBarCuentaLayout.setVerticalGroup(
            jd_ProgressBarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ProgressBarCuentaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel15)
                .addGap(67, 67, 67)
                .addComponent(jpb_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jLabel24.setText("Menu Usuario");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel24)
                .addContainerGap(681, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel24)
                .addContainerGap(525, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_menuUserLayout = new javax.swing.GroupLayout(jd_menuUser.getContentPane());
        jd_menuUser.getContentPane().setLayout(jd_menuUserLayout);
        jd_menuUserLayout.setHorizontalGroup(
            jd_menuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_menuUserLayout.setVerticalGroup(
            jd_menuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setText("Menu Solista");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel23)
                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel23)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_menuSolistaLayout = new javax.swing.GroupLayout(jd_menuSolista.getContentPane());
        jd_menuSolista.getContentPane().setLayout(jd_menuSolistaLayout);
        jd_menuSolistaLayout.setHorizontalGroup(
            jd_menuSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuSolistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_menuSolistaLayout.setVerticalGroup(
            jd_menuSolistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuSolistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel25.setText("Menu Banda");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel25)
                .addContainerGap(658, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel25)
                .addContainerGap(550, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_menuBandaLayout = new javax.swing.GroupLayout(jd_menuBanda.getContentPane());
        jd_menuBanda.getContentPane().setLayout(jd_menuBandaLayout);
        jd_menuBandaLayout.setHorizontalGroup(
            jd_menuBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_menuBandaLayout.setVerticalGroup(
            jd_menuBandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lab7_Miguel Rojas");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jb_login.setText("Iniciar Sesion");
        jb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginMouseClicked(evt);
            }
        });

        jb_registrarse.setText("Registrarse");
        jb_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarseMouseClicked(evt);
            }
        });

        cb_tipo_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Cuenta", "Artista", "Usuario" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usuarioMain)
                            .addComponent(pf_passwordMain, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addComponent(cb_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jb_registrarse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(jb_login)
                .addGap(152, 152, 152))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_usuarioMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(pf_passwordMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_login)
                    .addComponent(jb_registrarse))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearUsuarioMouseClicked
        // TODO add your handling code here:

        String user = null, password = null, nombre = null;
        int edad;
        boolean crear = true;

        if (tf_usuarioU.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearUsuario, "Debe Ingresar un usuario");
            crear = false;
        } else {
            user = tf_usuarioU.getText();
        }

        if (pf_passwordUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearUsuario, "Debe Ingresar una Contraseña");
            crear = false;
        } else {
            password = pf_passwordUser.getText();
        }

        if (tf_nombreUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearUsuario, "Debe Ingresar un Nombre");
            crear = false;
        } else {
            nombre = tf_nombreUser.getText();
        }

        edad = (int) js_edadUser.getValue();

        if (crear) {
            try {
                Usuarios u = new Usuarios(user, password, nombre, edad);
                au.getLista_usuarios().add(u);
                au.escribirArchivoU();//Agregar a Archivo Binario

                tf_nombreUser.setText("");
                pf_passwordUser.setText("");
                tf_nombreUser.setText("");
                jd_crearUsuario.dispose();
                abrirProgressbar();
                accion = new Accion(jpb_cuenta);
                accion.start();
                JOptionPane.showMessageDialog(jd_crearUsuario, "Se creo con exito el usuario");

                this.setVisible(true);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jb_crearUsuarioMouseClicked

    private void jb_crearSolistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearSolistaMouseClicked
        // TODO add your handling code here:

        String usuario = null, password = null, nombre = null, generoMusic = null;
        int edad_solista;

        boolean registrar = true;
        if (tf_usuarioSolista.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearSolista, "Falta un usuario");
            registrar = false;
        } else {
            usuario = tf_usuarioSolista.getText();
        }

        if (pf_passwordSolista.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearSolista, "Falta la Contraseña");
            registrar = false;
        } else {
            password = pf_passwordSolista.getText();
        }

        if (tf_nombreSolista.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearSolista, "Falta el Nombre");
            registrar = false;
        } else {
            nombre = tf_nombreSolista.getText();
        }

        if (tf_generoMusicalSolista.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearSolista, "Falta el Genero de Musica");
            registrar = false;
        } else {
            generoMusic = tf_generoMusicalSolista.getText();
        }

        edad_solista = (int) js_edadSolista.getValue();

        if (registrar) {
            try {
                Solistas s = new Solistas(edad_solista, usuario, password, nombre, generoMusic);
                //Escribir en Archivo Binario
                as.getLista_solistas().add(s);
                as.escribirArchivoS();
                //Progress Bar

                //
                JOptionPane.showMessageDialog(jd_crearSolista, "Se registro con exito el Solista");
                tf_usuarioSolista.setText("");
                pf_passwordSolista.setText("");
                tf_nombreSolista.setText("");
                tf_generoMusicalSolista.setText("");
                js_edadSolista.setValue(0);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jb_crearSolistaMouseClicked

    private void jb_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarseMouseClicked
        // TODO add your handling code here:

        if (cb_tipo_usuario.getSelectedItem() == "Tipo de Cuenta") {
            JOptionPane.showMessageDialog(this, "Debe Elegir un tipo de Cuenta para Registrarse");
        } else if (cb_tipo_usuario.getSelectedItem() == "Artista") {

            try {
                int input = Integer.parseInt(JOptionPane.showInputDialog(this, "Eliga tipo de Artista\n[1] Solista\n[2] Banda"));
                if (input == 1) {
                    tf_usuarioMain.setText("");
                    pf_passwordMain.setText("");
                    cb_tipo_usuario.setSelectedIndex(0);
                    this.setVisible(false);
                    jd_crearSolista.setModal(true);
                    jd_crearSolista.pack();
                    jd_crearSolista.setLocationRelativeTo(this);
                    jd_crearSolista.setVisible(true);
                } else if (input == 2) {
                    tf_usuarioMain.setText("");
                    pf_passwordMain.setText("");
                    cb_tipo_usuario.setSelectedIndex(0);
                    this.setVisible(false);
                    jd_crearBanda.setModal(true);
                    jd_crearBanda.pack();
                    jd_crearBanda.setLocationRelativeTo(this);
                    jd_crearBanda.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Debe Ingresar un Tipo Valido");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            //Abre la de Registrar Usuario Simple
            tf_usuarioMain.setText("");
            pf_passwordMain.setText("");
            cb_tipo_usuario.setSelectedIndex(0);
            this.setVisible(false);
            jd_crearUsuario.setModal(true);
            jd_crearUsuario.pack();
            jd_crearUsuario.setLocationRelativeTo(this);
            jd_crearUsuario.setVisible(true);

        }
    }//GEN-LAST:event_jb_registrarseMouseClicked

    private void jb_registrarBandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarBandaMouseClicked
        // TODO add your handling code here:
        String usuario = null, password = null, nombre = null, generoMusic = null;
        int num_integrantes;

        boolean registrar = true;
        if (tf_usuarioBanda.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearBanda, "Falta un usuario");
            registrar = false;
        } else {
            usuario = tf_usuarioBanda.getText();
        }

        if (pf_passwordBanda.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearBanda, "Falta la Contraseña");
            registrar = false;
        } else {
            password = pf_passwordBanda.getText();
        }

        if (tf_nombreBanda.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearBanda, "Falta el Nombre");
            registrar = false;
        } else {
            nombre = tf_nombreBanda.getText();
        }

        if (tf_generoM_banda.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_crearBanda, "Falta el Genero de Musica");
            registrar = false;
        } else {
            generoMusic = tf_generoM_banda.getText();
        }

        num_integrantes = (int) js_integrantes.getValue();

        if (registrar) {
            try {
                Banda b = new Banda(num_integrantes, usuario, password, nombre, generoMusic);
                ab.getLista_Bandas();
                ab.escribirArchivo_B();
                JOptionPane.showMessageDialog(jd_crearBanda, "Se Registro con Exito la Banda");
                //Hacer progress Bar
                tf_usuarioBanda.setText("");
                pf_passwordBanda.setText("");
                tf_generoM_banda.setText("");
                tf_nombreBanda.setText("");
                js_integrantes.setValue(0);
                jd_crearBanda.dispose();
                this.setVisible(true);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jb_registrarBandaMouseClicked

    private void jb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginMouseClicked
        // TODO add your handling code here:

        String usuario = null, password = null;
        String cuenta = null;

        boolean iniciar = true;
        boolean true_login = true;
        if (tf_usuarioMain.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar su Usuario");
            iniciar = false;
        } else {
            usuario = tf_usuarioMain.getText();
        }

        if (pf_passwordMain.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar su Contraseña");
            iniciar = false;
        } else {
            password = pf_passwordMain.getText();
        }

        if (cb_tipo_usuario.getSelectedItem().equals("Tipo de Cuenta")) {
            JOptionPane.showMessageDialog(this, "Debe Elegir un tipo de cuenta");
            iniciar = false;
        }

        if (iniciar) {
            //Check si la cuenta existe
            if (cb_tipo_usuario.getSelectedItem().equals("Solista")) {

                for (int i = 0; i < as.getLista_solistas().size(); i++) {

                    if (as.getLista_solistas().get(i).getUsuario().equals(usuario)
                            && as.getLista_solistas().get(i).getPassword().equals(password)) {
                        //la cuenta existe
                    } else {
                        true_login = false;
                    }
                }

            } else if (cb_tipo_usuario.getSelectedItem().equals("Banda")) {

                for (int i = 0; i < ab.getLista_Bandas().size(); i++) {
                    if (ab.getLista_Bandas().get(i).getUsuario().equals(usuario) && ab.getLista_Bandas().get(i).getPassword().equals(password)) {
                        //Existe la Cuenta
                    } else {
                        true_login = false;
                    }
                }

            } else {
                //Va buscar a un usuario normal
                for (int i = 0; i < au.getLista_usuarios().size(); i++) {
                    if (au.getLista_usuarios().get(i).getUsuario().equals(usuario) && au.getLista_usuarios().get(i).getPassword().equals(password)) {
                        //Existe la Cuenta
                    } else {
                        true_login = false;
                    }
                }

            }
        }
        if (true_login == false) {
            JOptionPane.showMessageDialog(this, "No existe el Usuario o es incorrecta la Informacion");
        } else {
            if (true_login && cb_tipo_usuario.getSelectedItem().equals("Solista")) {
                this.dispose();
                jd_menuSolista.setModal(true);
                jd_menuSolista.pack();
                jd_menuSolista.setLocationRelativeTo(this);
                jd_menuSolista.setVisible(true);

            } else if (true_login && cb_tipo_usuario.getSelectedItem().equals("Banda")) {
                this.dispose();
                jd_menuBanda.setModal(true);
                jd_menuBanda.pack();
                jd_menuBanda.setLocationRelativeTo(this);
                jd_menuBanda.setVisible(true);

            } else if (true_login && cb_tipo_usuario.getSelectedItem().equals("Usuario")) {

                if (usuario.equals("leobanegas") && password.equals("99")) {
                    //Abrir Menu de Leo
                    this.dispose();
                    jd_menuLeo.setModal(true);
                    jd_menuLeo.pack();
                    jd_menuLeo.setLocationRelativeTo(this);
                    jd_menuLeo.setVisible(true);

                } else {
                    this.dispose();
                jd_menuUser.setModal(true);
                jd_menuUser.pack();
                jd_menuUser.setLocationRelativeTo(this);
                jd_menuUser.setVisible(true);
                }
 
            } else {
                //do nothing
            }
        }

    }//GEN-LAST:event_jb_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_tipo_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jb_crearSolista;
    private javax.swing.JButton jb_crearUsuario;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_registrarBanda;
    private javax.swing.JButton jb_registrarse;
    private javax.swing.JDialog jd_ProgressBarCuenta;
    private javax.swing.JDialog jd_crearBanda;
    private javax.swing.JDialog jd_crearSolista;
    private javax.swing.JDialog jd_crearUsuario;
    private javax.swing.JDialog jd_menuBanda;
    private javax.swing.JDialog jd_menuLeo;
    private javax.swing.JDialog jd_menuSolista;
    private javax.swing.JDialog jd_menuUser;
    private javax.swing.JProgressBar jpb_cuenta;
    private javax.swing.JSpinner js_edadSolista;
    private javax.swing.JSpinner js_edadUser;
    private javax.swing.JSpinner js_integrantes;
    private javax.swing.JPasswordField pf_passwordBanda;
    private javax.swing.JPasswordField pf_passwordMain;
    private javax.swing.JPasswordField pf_passwordSolista;
    private javax.swing.JPasswordField pf_passwordUser;
    private javax.swing.JTextField tf_generoM_banda;
    private javax.swing.JTextField tf_generoMusicalSolista;
    private javax.swing.JTextField tf_nombreBanda;
    private javax.swing.JTextField tf_nombreSolista;
    private javax.swing.JTextField tf_nombreUser;
    private javax.swing.JTextField tf_usuarioBanda;
    private javax.swing.JTextField tf_usuarioMain;
    private javax.swing.JTextField tf_usuarioSolista;
    private javax.swing.JTextField tf_usuarioU;
    // End of variables declaration//GEN-END:variables

    Admin_Usuario au = new Admin_Usuario("./Usuarios.marh");
    Admin_Bandas ab = new Admin_Bandas("./Bandas.marh");
    Admin_Solistas as = new Admin_Solistas("./Solistas.marh");
    Accion accion;

    public void abrirProgressbar() {

        jd_ProgressBarCuenta.setModal(true);
        jd_ProgressBarCuenta.pack();
        jd_ProgressBarCuenta.setLocationRelativeTo(jd_crearUsuario);
        jd_ProgressBarCuenta.setVisible(true);
    }
}
